spring:
  ai:
    openai:
      api-key: ""
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        options:
          model: gemini-2.5-flash   # or gemini-2.5-pro
        completions-path: /chat/completions
      embedding:
        options:
          model: text-embedding-004
        base-url: https://generativelanguage.googleapis.com/v1beta/openai
        api-key: ""
        embeddings-path: /embeddings
